name: Release and Publish

on:
  release:
  types: [published]

env:
  NODE_VERSION: 12

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies and Build
        run: |
          npm ci
          npm run build-dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: pelican-release
          path: "dist/"

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: release

    steps:
      - name: Download package
        uses: actions/download-artifact@v2
        with:
          name: pelican-release

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://npm.pkg.github.com'
        
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
